import maplibregl from 'maplibre-gl'

export function buildMapStyle(): maplibregl.StyleSpecification {
  return {
    version: 8,
    name: 'UrbanPulse',
    center: [30.3141, 59.9386],
    zoom: 11,
    sources: {
      maptiler: {
        type: 'vector',
        url: 'https://tiles.openfreemap.org/planet',
      },
      analytics: {
        type: 'vector',
        tiles: ['http://localhost/tiles/analytics/{z}/{x}/{y}.pbf'],
        minzoom: 6,
        maxzoom: 15,
      },
    },
    sprite: 'https://tiles.openfreemap.org/styles/liberty/sprite',
    glyphs: 'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf',
    light: {
      anchor: 'viewport',
      color: '#fcfeff',
      intensity: 0.15,
    },
    layers: [
      {
        id: 'background',
        type: 'background',
        paint: {
          'background-color': [
            'interpolate', ['exponential', 1.5], ['zoom'],
            1, '#DEE2E6',
            6, '#F8F9FA',
          ],
        },
      },
      {
        id: 'landuse_grass',
        type: 'fill',
        source: 'maptiler',
        'source-layer': 'landuse',
        filter: ['in', 'class', 'grass', 'park', 'garden', 'recreation_ground'],
        paint: { 'fill-color': '#e9f5e4' },
      },
      {
        id: 'natural_wood',
        type: 'fill',
        source: 'maptiler',
        'source-layer': 'landuse',
        filter: ['in', 'class', 'wood', 'forest'],
        paint: {
          'fill-color': [
            'interpolate', ['exponential', 1.5], ['zoom'],
            1, '#e9f5e4',
            13, '#daebd1',
          ],
        },
      },
      {
        id: 'landuse_cemetery',
        type: 'fill',
        source: 'maptiler',
        'source-layer': 'landuse',
        filter: ['==', 'class', 'cemetery'],
        minzoom: 10,
        paint: { 'fill-color': '#e5f0df' },
      },
      {
        id: 'landuse_industrial',
        type: 'fill',
        source: 'maptiler',
        'source-layer': 'landuse',
        filter: ['==', 'class', 'industrial'],
        minzoom: 11,
        paint: { 'fill-color': '#f0ece4' },
      },
      {
        id: 'water',
        type: 'fill',
        source: 'maptiler',
        'source-layer': 'water',
        paint: {
          'fill-color': [
            'interpolate', ['exponential', 1.5], ['zoom'],
            1, '#343A40',
            6, '#adc7de',
          ],
        },
      },
      {
        id: 'waterway',
        type: 'line',
        source: 'maptiler',
        'source-layer': 'waterway',
        minzoom: 11,
        paint: {
          'line-color': '#adc7de',
          'line-width': [
            'interpolate', ['exponential', 1.6], ['zoom'],
            3, 0.6,
            18, 8,
          ],
        },
      },
      {
        id: 'analytics_hex',
        type: 'fill',
        source: 'analytics',
        'source-layer': 'hex',
        minzoom: 10,
        maxzoom: 15,
        filter: ['>', ['to-number', ['get', 's']], 0],
        paint: {
          'fill-color': ['interpolate', ['linear'], ['to-number', ['get', 's'], 0],
            10, '#749e71',
            20, '#83ad75',
            25, '#96bc77',
            30, '#b6cb7d',
            40, '#fad180',
            50, '#ecb17b',
            55, '#f19371',
            60, '#f17e71',
            70, '#c9756e',
            90, '#a86d6c',
          ],
          'fill-opacity': [
            'interpolate', ['linear'], ['zoom'],
            10, 0.7,
            13, 0.5,
            13.5, 0,
          ],
        },
      },
      {
        id: 'analytics_hex_air',
        type: 'fill',
        source: 'analytics',
        'source-layer': 'hex',
        minzoom: 6,
        layout: { visibility: 'none' },
        paint: {
          'fill-color': ['interpolate', ['linear'], ['to-number', ['get', 'impact'], 0],
            1000,  '#749e71',
            4000,  '#83ad75',
            5000,  '#96bc77',
            8000,  '#b6cb7d',
            10000, '#fad180',
            15000, '#ecb17b',
            20000, '#f19371',
            25000, '#f17e71',
            50000, '#c9756e',
            60000, '#a86d6c',
          ],
          'fill-opacity': 0.6,
        },
      },
      {
        id: 'analytics_hex_infrastructure',
        type: 'fill',
        source: 'analytics',
        'source-layer': 'hex',
        minzoom: 15,
        paint: {
          'fill-color': ['interpolate', ['linear'], ['to-number', ['get', 'infrastructure'], 0],
            0,   '#a86d6c',
            10,  '#c9756e',
            20,  '#f17e71',
            30,  '#f19371',
            40,  '#ecb17b',
            50,  '#fad180',
            100, '#b6cb7d',
            150, '#96bc77',
            200, '#83ad75',
            300, '#749e71',
          ],
        },
      },
      {
        id: 'analytics_hex_life_quality',
        type: 'fill',
        source: 'analytics',
        'source-layer': 'hex',
        minzoom: 6,
        layout: { visibility: 'none' },
        paint: {
          'fill-color': {
            property: 'life_quality',
            stops: [[1, '#f1a671'], [2, '#fad180'], [3, '#fff187'], [4, '#b6cb7d'], [5, '#83ad75']],
          },
        },
      },
      {
        id: 'boundary_country',
        type: 'line',
        source: 'maptiler',
        'source-layer': 'boundary',
        filter: ['==', 'admin_level', 2],
        maxzoom: 6,
        paint: {
          'line-width': 0.6,
          'line-opacity': 0.3,
          'line-color': '#6C757D',
        },
      },
      {
        id: 'boundary_admin',
        type: 'line',
        source: 'maptiler',
        'source-layer': 'boundary',
        filter: ['in', 'admin_level', 4, 6, 8],
        minzoom: 6,
        maxzoom: 12,
        paint: {
          'line-width': 0.8,
          'line-opacity': 0.4,
          'line-color': '#ccbfd6',
          'line-dasharray': [3, 2],
        },
      },
      {
        id: 'railway',
        type: 'line',
        source: 'maptiler',
        'source-layer': 'transportation',
        filter: ['==', 'class', 'rail'],
        minzoom: 6,
        paint: {
          'line-color': ['interpolate', ['linear'], ['zoom'], 6, '#c2b1a7', 12, '#b5a296'],
          'line-width': ['interpolate', ['linear'], ['zoom'], 6, 1, 14, 1.5, 16, 6],
        },
      },
      {
        id: 'transit_subway',
        type: 'line',
        source: 'maptiler',
        'source-layer': 'transportation',
        filter: ['==', 'class', 'transit'],
        minzoom: 9,
        paint: {
          'line-color': '#7a6fff',
          'line-width': ['interpolate', ['linear'], ['zoom'], 9, 1, 14, 3],
          'line-opacity': ['interpolate', ['linear'], ['zoom'], 9, 0.5, 14, 0.8],
        },
      },
      {
        id: 'roads_motorway_border',
        type: 'line',
        source: 'maptiler',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'motorway', 'trunk'],
        minzoom: 8,
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-width': ['interpolate', ['linear'], ['zoom'], 8, 5, 13, 10, 16, 14],
          'line-color': '#9b9fa3',
        },
      },
      {
        id: 'roads_motorway',
        type: 'line',
        source: 'maptiler',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'motorway', 'trunk'],
        minzoom: 6,
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-width': ['interpolate', ['linear'], ['zoom'], 7, 1.5, 9, 3.5, 13, 9.5, 16, 11],
          'line-color': '#ADB5BD',
        },
      },
      {
        id: 'roads_primary_border',
        type: 'line',
        source: 'maptiler',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'primary', 'secondary'],
        minzoom: 9,
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-width': ['interpolate', ['linear'], ['zoom'], 9, 4, 13, 7, 16, 12],
          'line-color': '#BEC5CC',
        },
      },
      {
        id: 'roads_primary',
        type: 'line',
        source: 'maptiler',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'primary', 'secondary'],
        minzoom: 8,
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-width': ['interpolate', ['linear'], ['zoom'], 8, 2.5, 9, 3.5, 13, 6, 16, 10],
          'line-color': '#CED4DA',
        },
      },
      {
        id: 'roads_minor_border',
        type: 'line',
        source: 'maptiler',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'tertiary', 'minor', 'service'],
        minzoom: 12,
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-width': ['interpolate', ['linear'], ['zoom'], 12, 3, 16, 9],
          'line-color': '#DEE2E6',
        },
      },
      {
        id: 'roads_minor',
        type: 'line',
        source: 'maptiler',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'tertiary', 'minor', 'service'],
        minzoom: 12,
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-width': ['interpolate', ['linear'], ['zoom'], 12, 1, 16, 7],
          'line-color': '#E9ECEF',
        },
      },
      {
        id: 'roads_path',
        type: 'line',
        source: 'maptiler',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'path', 'pedestrian'],
        minzoom: 14,
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-width': ['interpolate', ['linear'], ['zoom'], 15, 0.9, 18, 1.9],
          'line-color': '#ffffff',
        },
      },
      {
        id: 'buildings_3d',
        type: 'fill-extrusion',
        source: 'maptiler',
        'source-layer': 'building',
        minzoom: 13,
        paint: {
          'fill-extrusion-height': ['interpolate', ['linear'], ['zoom'], 14, 0, 15, ['get', 'render_height']],
          'fill-extrusion-color': ['interpolate', ['linear'], ['zoom'], 13, '#e3e3e3', 14, '#DDDDDD'],
          'fill-extrusion-opacity': 1,
          'fill-extrusion-vertical-gradient': true,
        },
      },
      {
        id: 'road_names',
        type: 'symbol',
        source: 'maptiler',
        'source-layer': 'transportation_name',
        minzoom: 8,
        layout: {
          'text-size': 12,
          'symbol-placement': 'line',
          'text-padding': 1,
          'text-rotation-alignment': 'map',
          'text-pitch-alignment': 'viewport',
          'text-field': ['coalesce', ['get', 'name:ru'], ['get', 'name']],
          'text-font': ['Noto Sans Regular'],
          'text-letter-spacing': 0.1,
        },
        paint: {
          'text-color': '#81888f',
          'text-halo-color': '#ffffff',
          'text-halo-width': 2,
        },
      },
      {
        id: 'place_city',
        type: 'symbol',
        source: 'maptiler',
        'source-layer': 'place',
        filter: ['in', 'class', 'city', 'town', 'village'],
        minzoom: 8,
        maxzoom: 13,
        layout: {
          'text-field': ['coalesce', ['get', 'name:ru'], ['get', 'name']],
          'text-font': ['Noto Sans Bold'],
          'text-size': ['interpolate', ['linear'], ['zoom'], 8, 12, 13, 15],
          'text-max-width': 7,
        },
        paint: {
          'text-color': '#8a8d91',
          'text-halo-color': '#F8F9FA',
          'text-halo-width': 1.7,
        },
      },
      {
        id: 'place_country',
        type: 'symbol',
        source: 'maptiler',
        'source-layer': 'place',
        filter: ['==', 'class', 'country'],
        layout: {
          'text-field': ['coalesce', ['get', 'name:ru'], ['get', 'name']],
          'text-font': ['Noto Sans Bold'],
          'text-size': ['interpolate', ['linear'], ['zoom'], 1, 13, 5, 17],
        },
        paint: {
          'text-color': '#6C757D',
          'text-halo-color': '#ffffff',
          'text-halo-width': 1,
        },
      },
      {
        id: 'ecology_poi',
        type: 'symbol',
        source: 'analytics',
        'source-layer': 'ecology_poi',
        minzoom: 6,
        layout: {
          'icon-image': ['get', 'poi_type'],
          'icon-size': ['interpolate', ['linear'], ['zoom'], 6, 0.3, 9, 0.6, 14, 1],
          'icon-allow-overlap': true,
          'text-field': ['step', ['zoom'], '', 12.1, ['get', 'name']],
          'text-font': ['Noto Sans Bold'],
          'text-size': 14,
          'text-offset': [0, 1.9],
          'text-anchor': 'top',
        },
        paint: {
          'text-color': '#696969',
          'text-halo-color': '#ffffff',
          'text-halo-width': 2,
        },
      },
      {
        id: 'infrastructure_poi',
        type: 'symbol',
        source: 'analytics',
        'source-layer': 'infrastructure_poi',
        minzoom: 15,
        layout: {
          'icon-image': ['get', 'poi_type'],
          'icon-size': ['interpolate', ['linear'], ['zoom'], 6, 0.3, 9, 0.6, 14, 1],
          'icon-allow-overlap': ['step', ['zoom'], false, 12, true],
          'text-field': ['get', 'name'],
          'text-font': ['Noto Sans Regular'],
          'text-size': ['interpolate', ['linear'], ['zoom'], 15, 13, 17, 15],
          'text-offset': [0, 1.5],
          'text-anchor': 'top',
        },
        paint: {
          'text-color': ['match', ['get', 'poi_type'],
            'shop', '#bd5e2f',
            'kindergarten', '#c9a244',
            'school', '#5c8760',
            'clinic', '#2b4a5e',
            '#22665b',
          ],
          'text-halo-color': '#ffffff',
          'text-halo-width': 2,
        },
      },
    ],
  }
}
